language: java

jdk:
  - oraclejdk8

notifications:
  email: true

install: true

script: mvn clean install --settings .travis.settings.xml

deploy:
  provider: script
  script: mvn deploy --settings .travis.settings.xml
  skip_cleanup: true
  on:
    tags: true
