language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

install: true

script:
- mvn clean install

#after_success:
# - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: bintray
    file: bintray-config.json
    user: $BINTRAY_USER
    key:  $BINTRAY_APIKEY
    skip_cleanup: true
    on:
      tags: true
      repo: watson-developer-cloud/java-sdk-core
    dry_run: true
#   - provider: releases
#     api_key: $GITHUB_OAUTH_TOKEN
#     file: xxx
#     skip_cleanup: true
#     on:
#       tags: true
#       repo: watson-developer-cloud/java-sdk-core
#     dry_run: true

notifications:
  email: true
