language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

install: true

# For a tagged build, we'll set the maven artifact version #.
before_script:
- env
- echo "TRAVIS_TAG = '${TRAVIS_TAG}'"
- '[ "${TRAVIS_TAG}" != "" ] && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false || true'

script:
- mvn clean package

# If we're going to deploy, we first resolve variables in our bintray config.
before_deploy:
- cat bintray-config.template | envsubst >bintray-config.json
- cat bintray-config.json

deploy:
  - provider: bintray
    file: bintray-config.json
    user: $BINTRAY_USER
    key:  $BINTRAY_APIKEY
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file:
      - target/java-sdk-core-*.jar
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: true
