language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

install: true

before_script:
- env
- '[ !-z "${TRAVIS_TAG}" ] && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false'

script:
- mvn clean package

before_deploy:
- cat bintray-config.template | envsubst > bintray-config.json


deploy:
  - provider: bintray
    file: bintray-config.json
    user: $BINTRAY_USER
    key:  $BINTRAY_APIKEY
    skip_cleanup: true
    on:
      tags: true
      repo: watson-developer-cloud/java-sdk-core
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - target/java-sdk-core-${TRAVIS_TAG}.jar
      - target/java-sdk-core-${TRAVIS_TAG}-sources.jar
      - target/java-sdk-core-${TRAVIS_TAG}-javadoc.jar
    skip_cleanup: true
    on:
      tags: true
      repo: watson-developer-cloud/java-sdk-core
    dry_run: true

notifications:
  email: true
